### ISSUE TITLE
Convert checklists to YAML

### ISSUE THREAD

**Issue by afeld** [18F/onboarding-documents#11]
We can then render them with Jekyll, which will make updating this a lot easier than editing blocks of HTML. Requires #10 for using 18F Pages, unless we want to put it behind authentication (which I don't think is necessary).

**Comment by melodykramer** [comment]
@afeld could you help me with this?

**Comment by afeld** [comment]
@melodykramer Sorry for dropping the ball on this. Presumably no longer relevant?

/cc @anthonygarvan @andrewmaier

**Comment by afeld** [comment]
Another idea, as I [mentioned in Slack](https://18f.slack.com/archives/checklistomania/p1452735194000004):

> at my last company, we had a repository for onboarding, and we had issue templates that we would use to keep track of onboarding steps for any new person. we're doing something similar for #compliance-toolkit: https://pages.18f.gov/before-you-ship/ato/checklist/ ... come to think of it, set that up for team member onboarding to C2: https://github.com/18F/C2/blob/master/doc/developer_onboarding.md

Just another option!

**Comment by melodykramer** [comment]
@anthonygarvan Would it be easier to import into Checklistomania if the files were in yaml? I don't think so. It's a slow slow through the repo... :)
