### ISSUE TITLE
Combine Engineering Facilitator and Dev checklists?

### ISSUE THREAD

**Issue by afeld** [18F/onboarding-documents#20]
Not quite sure that I understand why these two are split:

* https://github.com/18F/onboarding-documents/blob/master/Checklists/team-based-checklists/dev-new-hire-checklist.md
* https://github.com/18F/onboarding-documents/blob/master/Checklists/engineering-facilitator-checklist.md

Seems like the main difference is the **Who Has Information / Completes Task**, but that's already reflected in a column. Or am I misunderstanding the intention?

**Comment by afeld** [comment]
@melodykramer Would it be worth me doing this now? Or are you in the midst of moving the checklists to [checklistomania](https://github.com/18F/checklistomania)?

**Comment by melodykramer** [comment]
feel free! It's a slow move-over...
