### ISSUE TITLE
place for offboarding checklist?

### ISSUE THREAD

**Issue by afeld** [18F/onboarding-documents#24]
Our offboarding tasks our currently listed in [a spreadsheet](https://docs.google.com/spreadsheets/d/1IlFY5AAvTyuS7yDHk5_odJGHYZDU_MN9HNGKJ2zXwi0/edit)...maybe it would make sense to put them in this repository, even though "onboarding" is in the title?

/cc @NoahKunin @lsgitter @ethanheppner @jamiealbrecht @MKathrynC @martyspence https://github.com/18F/DevOps/issues/524

**Comment by afeld** [comment]
Something that @melodykramer caught:

* [Remove ownership of any Ruby gems](http://guides.rubygems.org/command-reference/#gem-owner) (see https://rubygems.org/profiles/USERNAME for the list)
* [Remove from the NPM organization](https://docs.npmjs.com/orgs/teams#removing-a-user-from-a-team)

**Comment by afeld** [comment]
@hollyallen pointed out there's an [offboarding procedure doc](https://docs.google.com/document/d/120V8TFeX9jU_bw98KLGjQwKHowFImWozEvLgfOlRMoo/edit) as well.

/cc @JenTress

**Comment by fureigh** [comment]
Another catch for the list:
* Check whether the employee is the sole owner of any 18F GitHub repositories. Add other folks or transfer ownership accordingly.

(In theory `about.yml` could be a source of this info, though I hesitate to suggest that at the moment.)

More generalized version: check whether this person is the bus factor for any projects and plan accordingly.

**Comment by afeld** [comment]
Also worth mentioning explicitly: past offboarding (from Engineering, especially) seems to have involved looking for [a prior offboarding issue in the DevOps repo](https://github.com/18F/DevOps/issues?utf8=%E2%9C%93&q=is%3Aissue+%22off+board%22+in%3Atitle) and copying it to a new one...hence the title of https://github.com/18F/DevOps/issues/524.

**Comment by afeld** [comment]
@fureigh Do you mean if it's under their account, or if they are the only Collaborator on a repository? #admins-github can always grant access to additional people, so not a huge deal if that doesn't happen as part of offboarding.

**Comment by fureigh** [comment]
@afeld I meant the latter (if they're the only Collaborator on a repository). I'm not concerned about the technical implications — as you said, #admins-github can grant access — but if a repo is quietly orphaned, we risk any new pull requests and issues going into a void. Ran across this issue with https://github.com/18F/wg-diversity/ earlier this week.

**Comment by jeremiak** [comment]
@afeld I think it would be great to include the offboarding list here!

**Comment by lsgitter** [comment]
@jeremiak we may want to clean it up before adding it to the handbook. It only meant to be used internally so it is not as clean as it could be. Also, if may need to be updated in a few places.
