### ISSUE TITLE
Broken Checklist Links

### ISSUE THREAD

**Issue by lauraGgit** [18F/onboarding-documents#26]
This is an ongoing thread of broken links during my onboarding.

**Comment by lauraGgit** [comment]
Day 2: Step 2: “Make your Macbook is secure” has a broken link for the instructions. It seems to be a rel link vs. full link issue.

**Comment by afeld** [comment]
* [ ] Set up [Markdown Proofer](https://github.com/afeld/markdown_proofer)

**Comment by lauraGgit** [comment]
*First Week*
6	☐	Sign up for listservs that interest you.	Instructions
The anchor to the header #listservs-and-communities on the linked [page](https://github.com/18F/handbook/blob/staging/articles/5-training-and-professional-development/classes/intro-to-product-and-open-source.md#listservs-and-communities) seems to no longer exist.

**Comment by porta-antiporta** [comment]
I submitted [https://github.com/18F/handbook/pull/486] for listservs ^^

**Comment by jeremiak** [comment]
@lauraGgit it looks like this specific issue is fixed so I'm going to close this issue. Please re-open if you still see problems.
